server:
  port: 8082

service:
  host:
    security: http://127.0.0.1:8080
    audit: http://127.0.0.1:8083

spring:
  datasource:
    url: jdbc:postgresql://90.156.219.8:5432/classifier
    username: classifier_app
    password: 855312