server:
  port: 8081

service:
  host:
    security: http://127.0.0.1:8080
    audit: http://127.0.0.1:8083

spring:
  datasource:
    url: jdbc:postgresql://90.156.219.8:5432/operations
    username: accop_app
    password: 855312